# Generated by Django 4.2.2 on 2023-11-15 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("solar_coordination_classic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="energypricing",
            name="active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="energypricing",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="studyrun",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
