# Generated by Django 4.2.2 on 2023-11-15 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "solar_coordination_classic",
            "0002_energypricing_active_energypricing_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar_coordination_classic.user",
            ),
        ),
        migrations.AddField(
            model_name="comfortcostslot",
            name="comfort_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar_coordination_classic.comfortprofile",
            ),
        ),
        migrations.AddField(
            model_name="solargeneration",
            name="solar_generation_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar_coordination_classic.solargenerationprofile",
            ),
        ),
        migrations.AddField(
            model_name="studyrun",
            name="condition",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar_coordination_classic.condition",
            ),
        ),
        migrations.AddField(
            model_name="studyrun",
            name="solar_generation_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar_coordination_classic.solargenerationprofile",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="study_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar_coordination_classic.studyrun",
            ),
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "comfort_profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solar_coordination_classic.comfortprofile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="solar_coordination_classic.user",
                    ),
                ),
            ],
        ),
    ]
