# Generated by Django 4.2.2 on 2023-11-15 16:15

from django.db import migrations

def add_default_energy_pricing(apps, schema_editor):
    EnergyPricing = apps.get_model('solar_coordination_classic', 'EnergyPricing')
    EnergyPricing(name="UK Energy Pricing", export_price = 0.05, import_price = 0.30, active = True).save()

def remove_default_energy_pricing(apps, schema_editor):
    EnergyPricing = apps.get_model('solar_coordination_classic', 'EnergyPricing')
    EnergyPricing.objects.filter(name="UK Energy Pricing").delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "solar_coordination_classic",
            "0003_booking_user_comfortcostslot_comfort_profile_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(code = add_default_energy_pricing, reverse_code = remove_default_energy_pricing),
    ]