# Generated by Django 4.2.2 on 2023-11-15 16:46

from django.db import migrations

def add_default_solar_gen_profile(apps, schema_editor):
    SolarGenerationProfile = apps.get_model('solar_coordination_classic', 'SolarGenerationProfile')
    SolarGenerationProfile(name="Sunny Autumn Day").save()

def remove_default_solar_gen_profile(apps, schema_editor):
    SolarGenerationProfile = apps.get_model('solar_coordination_classic', 'SolarGenerationProfile')
    SolarGenerationProfile.objects.filter(name="Sunny Autumn Day").delete()

class Migration(migrations.Migration):

    dependencies = [
        (
            "solar_coordination_classic",
            "0004_auto_20231115_1615",
        ),
    ]

    operations = [
        migrations.RunPython(code = add_default_solar_gen_profile, reverse_code = remove_default_solar_gen_profile),
    ]
