# Generated by Django 4.2.2 on 2023-11-16 15:40

from django.db import migrations

def add_default_solar_gen(apps, schema_editor):
    SolarGeneration = apps.get_model('solar_coordination_classic', 'SolarGeneration')
    SolarGenerationProfile = apps.get_model('solar_coordination_classic', 'SolarGenerationProfile')

    default_profile = SolarGenerationProfile.objects.get(name = "Sunny Autumn Day")
    hours = [i for i in range(1, 25)]
    solar_values = [0, 0, 0, 0, 0, 50, 200, 500, 1100, 1350, 2300, 2500, 3600, 2000, 1400, 1000, 790, 450, 70, 0, 0, 0, 0, 0]

    for hour, solar_value in zip(reversed(hours), solar_values):
        SolarGeneration(hour = hour, amount = solar_value, solar_generation_profile = default_profile).save()

def remove_default_solar_gen(apps, schema_editor):
    SolarGeneration = apps.get_model('solar_coordination_classic', 'SolarGeneration')
    SolarGenerationProfile = apps.get_model('solar_coordination_classic', 'SolarGenerationProfile')
    
    default_profile = SolarGenerationProfile.objects.get(name = "Sunny Autumn Day")

    SolarGeneration.objects.filter(solar_generation_profile = default_profile).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("solar_coordination_classic", "0005_auto_20231115_1646"),
    ]

    operations = [
        migrations.RunPython(code = add_default_solar_gen, reverse_code = remove_default_solar_gen),
    ]
