# Generated by Django 4.2.2 on 2023-11-27 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "solar_coordination_classic",
            "0007_condition_active_participant_condition_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="study_run",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="solar_coordination_classic.studyrun",
            ),
        ),
    ]
