# Generated by Django 4.2.2 on 2023-11-28 13:26

from django.db import migrations    

def add_new_default_solar_gen(apps, schema_editor):
    # Delete current solar gen values (they were in W not kW)
    SolarGeneration = apps.get_model('solar_coordination_classic', 'SolarGeneration')
    SolarGenerationProfile = apps.get_model('solar_coordination_classic', 'SolarGenerationProfile')
    
    default_profile = SolarGenerationProfile.objects.get(name = "Sunny Autumn Day")

    SolarGeneration.objects.filter(solar_generation_profile = default_profile).delete()
    # End of Delete current solar gen values (they were in W not kW)


    hours = [i for i in range(1, 25)]
    solar_values = [0, 0, 0, 0, 0, 2.991, 18.624, 35.096, 73.723, 99.672, 90.248, 85.128, 73.776, 54.992, 30.136, 22.016, 6.783, 3.823, 0, 0, 0, 0, 0, 0]

    for hour, solar_value in zip(reversed(hours), reversed(solar_values)):
        SolarGeneration(hour = hour, amount = solar_value, solar_generation_profile = default_profile).save()

def remove_default_solar_gen(apps, schema_editor):
    SolarGeneration = apps.get_model('solar_coordination_classic', 'SolarGeneration')
    SolarGenerationProfile = apps.get_model('solar_coordination_classic', 'SolarGenerationProfile')
    
    default_profile = SolarGenerationProfile.objects.get(name = "Sunny Autumn Day")

    SolarGeneration.objects.filter(solar_generation_profile = default_profile).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("solar_coordination_classic", "0008_participant_study_run"),
    ]

    operations = [
        migrations.RunPython(code = add_new_default_solar_gen, reverse_code = remove_default_solar_gen),
    ]