# Generated by Django 4.2.2 on 2023-11-29 11:04

from django.db import migrations

def add_default_comfort_profile(apps, schema_editor):
    ComfortProfile = apps.get_model('solar_coordination_classic', 'ComfortProfile')
    ComfortProfile(name="9am to 3pm").save()

def remove_default_comfort_profile(apps, schema_editor):
    ComfortProfile = apps.get_model('solar_coordination_classic', 'ComfortProfile')
    ComfortProfile.objects.filter(name="9am to 3pm").delete()

class Migration(migrations.Migration):

    dependencies = [
        (
            "solar_coordination_classic",
            "0010_remove_participant_study_run_studyrunallocation",
        ),
    ]

    operations = [
        migrations.RunPython(code = add_default_comfort_profile, reverse_code = remove_default_comfort_profile),
    ]
